spring:
  application:
    name: Spring OAuth2 template
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

management:
  endpoints:
    web:
      base-path: /sys
      exposure:
        include: 'health'

security:
  oauth2:
    signingKey: 61d11e20-af83-4dec-87da-58ab2485b348
    client:
      client-id: webui
      registered-redirect-uri: http://localhost:3000/token, /ui/token
      authorized-grant-types: implicit
      scope: write
      auto-approve-scopes: write
      resource-ids: spring-vue-oauth2
    resource:
      id: spring-vue-oauth2

